### ISSUE TITLE
Document how to set up a server with authentication enabled

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.org#109]
I've seen more than a few threads on the mailing list about this. People don't know how to do it and it's not intuitive. We need step by step instructions for setting up a server with authentication enabled that has an admin user that can do things.

**Comment by gunnaraasen** [comment]
This is addressed in the authentication docs #120.

There are a bunch of issues (influxdb/influxdb#2193 and influxdb/influxdb#2278) and a PR (influxdb/influxdb#2530) suggesting alternative bootstrapping methods, but nothing has been merged yet.
