### ISSUE TITLE
Some aggregation functions are not there

### ISSUE THREAD

**Issue by thecodeassassin** [influxdb/influxdb.org#125]
hey All,

It seems that there are some aggregations functions that really don't exist in influxdb such as distinct.

https://github.com/influxdb/influxdb.org/blob/master/source/docs/v0.9/query_language/aggregate_functions.md

https://github.com/influxdb/influxdb/blob/master/influxql/functions.go#L92

Should they be removed from the docs until they are added or am i missing something?

**Comment by beckettsean** [comment]
closed by #138
