### ISSUE TITLE
Question: 0.9 cluster guide

### ISSUE THREAD

**Issue by jogjayr** [influxdb/influxdb.org#130]
Duplicate of this issue (it was closed with a request to re-open on this repo):
https://github.com/influxdb/influxdb/issues/2571

Quoting from it:

" Current 0.9 documentation has done a good introduction to the how 0.9 clustering works.

I'd like to know about how to setup it. Basically, I want know about how to setup configurations for that (to try out influxdb clustering). Is there any place, I can look more about it?"

**Comment by beckettsean** [comment]
Closing issues in deprecated repo. New docs repo at influxdb/influxdb.com.

@jogjayr the clustering implementation for 0.9 is alpha right now, docs will follow once things settle enough to warrant the effort. Should be more clustering docs with 0.9.1 in a few weeks.
