### ISSUE TITLE
Documentation: How can we name databases and series?

### ISSUE THREAD

**Issue by lra** [influxdb/influxdb.org#51]
Hi,

I can't find anywhere what characters are allowed to name databases and series.
I'm working on a script that's gonna dynamically generate series names from another source and I'm scared some auto generated name wont' fit, e.g. "Blah's" or "a/b/c/".

Any pointer to the doc that specifies this?

**Comment by lra** [comment]
is it in the doc now?

**Comment by beckettsean** [comment]
pushing today. For 0.9 the answer is if the identifier (db name, tag name, field name, RP name, etc.) contains any character other than [A-Z,a-z,0-9,_] or if it starts with a digit it must be double-quoted. For 0.8 any identifier that contains any character other than [A-Z,a-z,0-9,_,.] must be double-quoted, but I'm not as confident in the 0.8 answer.

**Comment by lra** [comment]
Cool thanks, always helpful to know the constraints before hand.
FTR It's now mentioned in https://github.com/influxdb/influxdb.org/blob/master/source/docs/v0.9/introduction/getting_started.md
